### ISSUE TITLE
Error 404 when trying to manually up- or download

### ISSUE THREAD

**Issue by kayaj** [swisspost-yellowcube/magento-yellowcube#9]
- Magento 1.9.2.1
- Apache
- PHP 5.5.28
- magento-yellowcube Extension is fully configured

When I'm clicking on the button in the magento backend (ajax up- or download) nothing happens.
Checking in the console I found out, that the URL is a 404.
Both of the following URL's are 404's.
_http://www.webshop.tld/index.php/admin/admin/yellowcube_system_config_sync/download/key/f1o2o3b4a5r/?isAjax=true
http://www.webshop.tld/index.php/admin/admin/yellowcube_system_config_sync/upload/key/f1o2o3b4a5r/?isAjax=true_

**Anyone else had the same experience?**

![magento administration 2015-09-07 15-36-04](https://cloud.githubusercontent.com/assets/4310449/9717832/2fba82cc-5576-11e5-9a91-8b9531cde01a.jpg)
![magento administration 2015-09-07 15-36-36](https://cloud.githubusercontent.com/assets/4310449/9717844/4fb6d1e8-5576-11e5-92d7-baffe1a84d96.jpg)

**Comment by psavary** [comment]
Should be fine now, haven't had any complaints for a year on this front.
